//! `MatrixClient` trait — the mock boundary between the bot's sync loop
//! and the matrix-sdk (item 5.25).
//!
//! The real impl wraps `matrix-sdk` and yields three kinds of events: GPX
//! file bytes received in any joined room, `link` commands from users, and
//! replies to mentions. The test impl returns fixture events so the sync
//! loop can be exercised without a live Matrix connection.

use std::path::Path;

use async_trait::async_trait;
use matrix_sdk::{
    Client, Error, LoopCtrl, Room, RoomState,
    config::SyncSettings,
    media::{MediaFormat, MediaRequestParameters},
    ruma::{
        EventId, MilliSecondsSinceUnixEpoch, OwnedEventId, OwnedRoomId, OwnedUserId, RoomId,
        UserId,
        api::client::relations::{
            get_relating_events_with_rel_type, get_relating_events_with_rel_type_and_event_type,
        },
        events::{
            AnyMessageLikeEvent, TimelineEventType,
            reaction::ReactionEventContent,
            relation::{Annotation, InReplyTo, RelationType, Thread},
            room::{
                member::StrippedRoomMemberEvent,
                message::{
                    FileMessageEventContent, MessageType, OriginalSyncRoomMessageEvent, Relation,
                    RoomMessageEventContent,
                },
            },
        },
    },
    sync::SyncResponse,
};
use tokio::sync::mpsc;
use tokio::time::sleep;

use crate::matrix_auth::{MatrixLoginConfig, get_client};

const SEEN_REACTION_KEY: &str = "👀";
const RESPONSE_WINDOW_MILLIS: u64 = 24 * 60 * 60 * 1000;
const COMMAND_REPLY_TEXT: &str =
    "I do not understand that command, but I am awaiting your next GPX file.";

#[derive(Debug, Clone)]
pub struct GpxFileMetadata {
    pub filename: String,
    /// The Matrix user who sent the file.
    pub sender: OwnedUserId,
    pub room_id: OwnedRoomId,
    pub event_id: OwnedEventId,
}

/// Everything the sync loop can observe from Matrix.
#[derive(Debug)]
pub enum BotEvent {
    /// A `.gpx` file was sent in a joined room.
    GpxFile {
        bytes: Vec<u8>,
        metadata: GpxFileMetadata,
    },
    /// A user invoked the `link` command.
    LinkRequest {
        sender: OwnedUserId,
        room_id: OwnedRoomId,
        event_id: OwnedEventId,
    },
    /// A reply generated by a background task (e.g. the link poller),
    /// routed through the main loop so all Matrix I/O stays in one place.
    Reply {
        room_id: OwnedRoomId,
        event_id: OwnedEventId,
        text: String,
    },
}

type BotEventSender = mpsc::Sender<BotEvent>;
type BotEventSenderCtx =
    matrix_sdk::event_handler::Ctx<std::sync::Arc<tokio::sync::Mutex<BotEventSender>>>;

#[async_trait]
pub trait MatrixClient: Send + Sync {
    async fn wait_for_event(&self) -> anyhow::Result<BotEvent>;

    async fn send_text_reply(
        &self,
        room_id: &RoomId,
        event_id: &EventId,
        text: &str,
    ) -> anyhow::Result<()>;

    async fn send_html_reply(
        &self,
        room_id: &RoomId,
        event_id: &EventId,
        plain: &str,
        html: &str,
    ) -> anyhow::Result<()>;

    async fn send_reaction(
        &self,
        room_id: &RoomId,
        event_id: &EventId,
        key: &str,
    ) -> anyhow::Result<()>;

    /// Whether the bot has already reacted to `event_id` in `room_id` with
    /// any of the given reaction keys (e.g. ✅ / ❌).
    ///
    /// Used as a client-side idempotency filter: on restart, the bot
    /// re-sees messages it already processed and skipped them so it does
    /// not re-upload the GPX.
    async fn has_own_reaction(
        &self,
        room_id: &RoomId,
        event_id: &EventId,
        keys: &[&str],
    ) -> anyhow::Result<bool>;
}

pub struct MatrixSdkClient {
    client: Client,
    tx: std::sync::Arc<tokio::sync::Mutex<BotEventSender>>,
    rx: std::sync::Arc<tokio::sync::Mutex<mpsc::Receiver<BotEvent>>>,
}

impl MatrixSdkClient {
    /// Build a Matrix client that yields GPX files, `link` commands and
    /// replies to mentions received in joined rooms.
    ///
    /// The initial sync resumes from a previously persisted sync token in
    /// `sync_token_file` (falling back to a fresh sync when absent), and a
    /// background loop keeps syncing, persisting each response's `next_batch`
    /// so a restart does not re-deliver already-seen events.
    ///
    /// # Errors
    /// Returns an error if the Matrix client cannot be built, the login
    /// fails, or the initial sync does not complete.
    pub async fn new(
        login: &MatrixLoginConfig,
        session_file: &Path,
        sync_token_file: &Path,
    ) -> anyhow::Result<Self> {
        let client = get_client(login, session_file).await?;

        client.add_event_handler(on_stripped_state_member);

        let (tx, rx) = mpsc::channel::<BotEvent>(16);
        let tx = std::sync::Arc::new(tokio::sync::Mutex::new(tx));
        let rx = std::sync::Arc::new(tokio::sync::Mutex::new(rx));
        client.add_event_handler_context(tx.clone());
        client.add_event_handler(on_room_message);

        let settings = read_sync_token(sync_token_file)
            .map_or_else(SyncSettings::default, |prev| {
                SyncSettings::default().token(prev)
            });
        let initial_token = client.sync_once(settings).await?.next_batch;
        if let Err(e) = persist_sync_token(sync_token_file, &initial_token) {
            tracing::error!(
                "Failed to persist initial sync token to {}: {e:#}",
                sync_token_file.display()
            );
        }
        tracing::info!("Finished initial Matrix sync");

        let sync_client = client.clone();
        let sync_token_file = sync_token_file.to_owned();
        tokio::spawn(async move {
            // `sync_with_result_callback` syncs forever; the callback persists
            // each `next_batch` and swallows errors so the loop survives
            // transient failures (log-and-continue).
            if let Err(e) = sync_client
                .sync_with_result_callback(SyncSettings::default().token(initial_token), |result| {
                    persist_next_batch(&sync_token_file, result)
                })
                .await
            {
                tracing::error!("Matrix sync loop ended with error: {e}");
            }
        });

        Ok(Self { client, tx, rx })
    }

    /// A sender that background tasks (e.g. the link poller) can use to
    /// route [`BotEvent::Reply`] back through the main loop.
    #[must_use]
    pub fn event_sender(&self) -> std::sync::Arc<tokio::sync::Mutex<BotEventSender>> {
        self.tx.clone()
    }
}

/// Read the persisted sync token, if any. A missing file (or an unreadable
/// one, logged) falls back to a fresh sync — the server-side dedup makes a
/// re-sync of recent events safe.
fn read_sync_token(sync_token_file: &Path) -> Option<String> {
    match std::fs::read_to_string(sync_token_file) {
        Ok(token) => {
            let token = token.trim();
            if token.is_empty() {
                None
            } else {
                Some(token.to_owned())
            }
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
        Err(e) => {
            tracing::error!(
                "Failed to read sync token from {}: {e:#}",
                sync_token_file.display()
            );
            None
        }
    }
}

/// Write `token` to `sync_token_file`, creating any missing parent
/// directories.
///
/// # Errors
/// Returns an error if the parent directory cannot be created or the file
/// cannot be written.
fn persist_sync_token(sync_token_file: &Path, token: &str) -> anyhow::Result<()> {
    if let Some(parent) = sync_token_file.parent()
        && !parent.as_os_str().is_empty()
    {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(sync_token_file, token)?;
    Ok(())
}

/// `sync_with_result_callback` callback: persist each successful response's
/// `next_batch` to disk and keep syncing. Errors are logged and swallowed so
/// the loop keeps going (log-and-continue).
fn persist_next_batch(
    sync_token_file: &Path,
    result: Result<SyncResponse, Error>,
) -> std::future::Ready<Result<LoopCtrl, Error>> {
    match result {
        Ok(response) => {
            if let Err(e) = persist_sync_token(sync_token_file, &response.next_batch) {
                tracing::error!(
                    "Failed to persist sync token to {}: {e:#}",
                    sync_token_file.display()
                );
            }
        }
        Err(e) => tracing::error!("Matrix sync ended with error: {e}"),
    }
    std::future::ready(Ok(LoopCtrl::Continue))
}

#[async_trait]
impl MatrixClient for MatrixSdkClient {
    async fn wait_for_event(&self) -> anyhow::Result<BotEvent> {
        let mut rx = self.rx.lock().await;
        rx.recv()
            .await
            .ok_or_else(|| anyhow::anyhow!("matrix event channel closed"))
    }

    async fn send_text_reply(
        &self,
        room_id: &RoomId,
        event_id: &EventId,
        text: &str,
    ) -> anyhow::Result<()> {
        let room = self
            .client
            .get_room(room_id)
            .ok_or_else(|| anyhow::anyhow!("room {room_id} not found"))?;

        let mut content = RoomMessageEventContent::text_plain(text);
        content.relates_to = Some(Relation::Reply {
            in_reply_to: InReplyTo::new(event_id.to_owned()),
        });
        room.send(content).await?;
        Ok(())
    }

    async fn send_html_reply(
        &self,
        room_id: &RoomId,
        event_id: &EventId,
        plain: &str,
        html: &str,
    ) -> anyhow::Result<()> {
        let room = self
            .client
            .get_room(room_id)
            .ok_or_else(|| anyhow::anyhow!("room {room_id} not found"))?;

        let mut content = RoomMessageEventContent::text_html(plain, html);
        content.relates_to = Some(Relation::Reply {
            in_reply_to: InReplyTo::new(event_id.to_owned()),
        });
        room.send(content).await?;
        Ok(())
    }

    async fn send_reaction(
        &self,
        room_id: &RoomId,
        event_id: &EventId,
        key: &str,
    ) -> anyhow::Result<()> {
        let room = self
            .client
            .get_room(room_id)
            .ok_or_else(|| anyhow::anyhow!("room {room_id} not found"))?;

        let content =
            ReactionEventContent::new(Annotation::new(event_id.to_owned(), key.to_owned()));
        room.send(content).await?;
        Ok(())
    }

    async fn has_own_reaction(
        &self,
        room_id: &RoomId,
        event_id: &EventId,
        keys: &[&str],
    ) -> anyhow::Result<bool> {
        has_own_reaction(&self.client, room_id, event_id, keys).await
    }
}

/// Check whether `client`'s own user has reacted to `event_id` with any of
/// `keys`. matrix-sdk 0.11 has no `Room::event_relations`, so this uses the
/// raw ruma endpoint `GET /rooms/{roomId}/relations/{eventId}/m.annotation`.
///
/// Returns `Ok(false)` when the client has no logged-in user.
async fn has_own_reaction(
    client: &Client,
    room_id: &RoomId,
    event_id: &EventId,
    keys: &[&str],
) -> anyhow::Result<bool> {
    let Some(user_id) = client.user_id() else {
        return Ok(false);
    };

    let request = get_relating_events_with_rel_type::v1::Request::new(
        room_id.to_owned(),
        event_id.to_owned(),
        RelationType::Annotation,
    );
    let response = client.send(request).await?;

    for raw in response.chunk {
        let Ok(AnyMessageLikeEvent::Reaction(reaction)) = raw.deserialize() else {
            continue;
        };
        if reaction.sender() != user_id {
            continue;
        }
        let Some(original) = reaction.as_original() else {
            continue;
        };
        if keys.contains(&original.content.relates_to.key.as_str()) {
            return Ok(true);
        }
    }
    Ok(false)
}

async fn on_stripped_state_member(
    room_member: StrippedRoomMemberEvent,
    client: Client,
    room: Room,
) {
    let Some(user_id) = client.user_id() else {
        tracing::error!("Could not get user id from client");
        return;
    };
    if room_member.state_key != user_id {
        return;
    }

    tokio::spawn(async move {
        // Join first — request_encryption_state() before joining tends
        // to fail because the server won't serve state to non-members.
        let mut delay = 2u64;

        while let Err(err) = room.join().await {
            tracing::error!(
                "Failed to join room {} ({err:?}), retrying in {delay}s",
                room.room_id()
            );
            sleep(std::time::Duration::from_secs(delay)).await;
            if let Some(x) = delay.checked_mul(2) {
                delay = x;
            } else {
                tracing::error!("Delay got too large, aborting");
                return;
            }
            if delay > 3600 {
                tracing::error!("Can't join room {} ({err:?})", room.room_id());
                return;
            }
        }
        tracing::info!("Successfully joined room {}", room.room_id());

        // Now check whether the room is encrypted; leave if it is.
        if let Err(e) = room.request_encryption_state().await {
            tracing::warn!(
                "Could not request encryption state for room {} ({e}), \
                 staying joined anyway",
                room.room_id()
            );
        } else if !matches!(
            room.encryption_state(),
            matrix_sdk::EncryptionState::NotEncrypted
        ) {
            tracing::error!("Room {} is encrypted, leaving", room.room_id());
            if let Err(e) = room.leave().await {
                tracing::error!("Failed to leave room {}: {e}", room.room_id());
            }
        }
    });
}

async fn on_room_message(
    event: OriginalSyncRoomMessageEvent,
    room: Room,
    client: Client,
    tx: BotEventSenderCtx,
) {
    if room.state() != RoomState::Joined {
        return;
    }
    let Some(user_id) = client.user_id() else {
        tracing::error!("Could not get user id from client");
        return;
    };
    if event.sender == user_id {
        return;
    }

    match &event.content.msgtype {
        MessageType::File(file_content) => {
            handle_gpx_file(
                file_content,
                &room,
                &client,
                &tx,
                &event.sender,
                &event.event_id,
            )
            .await;
        }
        MessageType::Text(text_content) => {
            if is_link_command(&text_content.body, user_id.as_str()) {
                tracing::info!("Link command from {}", event.sender);
                let _ = tx
                    .lock()
                    .await
                    .send(BotEvent::LinkRequest {
                        sender: event.sender.clone(),
                        room_id: room.room_id().to_owned(),
                        event_id: event.event_id.clone(),
                    })
                    .await;
            } else {
                handle_text_mention(&client, &room, &event, user_id).await;
            }
        }
        _ => {}
    }
}

/// Downloads a `.gpx` file message and forwards it to the sync loop.
async fn handle_gpx_file(
    file_content: &FileMessageEventContent,
    room: &Room,
    client: &Client,
    tx: &BotEventSenderCtx,
    sender: &OwnedUserId,
    event_id: &OwnedEventId,
) {
    let filename = file_content.filename().to_owned();
    if !Path::new(&filename)
        .extension()
        .is_some_and(|ext| ext.eq_ignore_ascii_case("gpx"))
    {
        return;
    }

    // Skip messages the bot already handled (any own ✅/❌ reaction),
    // before paying for the media download. On an error, proceed anyway:
    // the server-side dedup makes a re-upload a no-op.
    if matches!(
        has_own_reaction(client, room.room_id(), event_id, &["✅", "❌"]).await,
        Ok(true)
    ) {
        tracing::info!("Skipping {filename}: bot already reacted to {}", event_id);
        return;
    }

    let bytes = match client
        .media()
        .get_media_content(
            &MediaRequestParameters {
                source: file_content.source.clone(),
                format: MediaFormat::File,
            },
            false,
        )
        .await
    {
        Ok(b) => b,
        Err(e) => {
            tracing::error!("Failed to download file {filename}: {e}");
            return;
        }
    };

    tracing::info!("Received GPX file: {filename}");
    let _ = tx
        .lock()
        .await
        .send(BotEvent::GpxFile {
            bytes,
            metadata: GpxFileMetadata {
                filename,
                sender: sender.clone(),
                room_id: room.room_id().to_owned(),
                event_id: event_id.clone(),
            },
        })
        .await;
}

async fn handle_text_mention(
    client: &Client,
    room: &Room,
    event: &OriginalSyncRoomMessageEvent,
    bot_id: &UserId,
) {
    if !is_mentioned(event, bot_id) {
        return;
    }

    if !within_response_window(event.origin_server_ts) {
        tracing::info!("Ignoring {}: outside 24h response window", event.event_id);
        return;
    }

    if already_seen(client, room, &event.event_id).await {
        tracing::info!("Ignoring {}: already acknowledged", event.event_id);
        return;
    }

    if let Err(e) = room.send(build_command_reply(event)).await {
        tracing::error!("Failed to send command reply in {}: {e}", room.room_id());
        return;
    }

    if let Err(e) = room
        .send(ReactionEventContent::new(Annotation::new(
            event.event_id.clone(),
            SEEN_REACTION_KEY.to_owned(),
        )))
        .await
    {
        tracing::error!("Failed to send seen reaction: {e}");
    }
}

fn is_mentioned(event: &OriginalSyncRoomMessageEvent, bot_id: &UserId) -> bool {
    event
        .content
        .mentions
        .as_ref()
        .is_some_and(|mentions| mentions.user_ids.iter().any(|id| id == bot_id))
}

fn within_response_window(ts: MilliSecondsSinceUnixEpoch) -> bool {
    let now = MilliSecondsSinceUnixEpoch::now().get();
    let sent = ts.get();
    u64::from(now).saturating_sub(u64::from(sent)) <= RESPONSE_WINDOW_MILLIS
}

async fn already_seen(client: &Client, room: &Room, event_id: &EventId) -> bool {
    let request = get_relating_events_with_rel_type_and_event_type::v1::Request::new(
        room.room_id().to_owned(),
        event_id.to_owned(),
        RelationType::Annotation,
        TimelineEventType::Reaction,
    );

    let Ok(response) = client.send(request).await else {
        return false;
    };

    for raw in response.chunk {
        let Ok(AnyMessageLikeEvent::Reaction(reaction)) = raw.deserialize() else {
            continue;
        };
        let Some(original) = reaction.as_original() else {
            continue;
        };
        if original.content.relates_to.key == SEEN_REACTION_KEY {
            return true;
        }
    }
    false
}

fn build_command_reply(event: &OriginalSyncRoomMessageEvent) -> RoomMessageEventContent {
    let root_event_id = match &event.content.relates_to {
        Some(Relation::Thread(thread)) => thread.event_id.clone(),
        _ => event.event_id.clone(),
    };

    let mut content = RoomMessageEventContent::text_plain(COMMAND_REPLY_TEXT);
    content.relates_to = Some(Relation::Thread(Thread::reply(
        root_event_id,
        event.event_id.clone(),
    )));
    content
}

/// Whether a message body is a `link` command — bare `link`, `!link`, or
/// a mention like `@health-bot link` (case-insensitive).
fn is_link_command(body: &str, bot_user_id: &str) -> bool {
    let trimmed = body.trim();
    let without_bang = trimmed.strip_prefix('!').unwrap_or(trimmed).trim();
    let without_mention = without_bang
        .strip_prefix(bot_user_id)
        .unwrap_or(without_bang)
        .trim();
    without_mention.eq_ignore_ascii_case("link")
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, unsafe_code)]

    use std::time::UNIX_EPOCH;

    use matrix_sdk::ruma::{
        MilliSecondsSinceUnixEpoch, OwnedEventId, OwnedUserId,
        events::{
            Mentions, MessageLikeUnsigned,
            relation::Thread,
            room::message::{
                MessageType, OriginalSyncRoomMessageEvent, Relation, RoomMessageEventContent,
                RoomMessageEventContentWithoutRelation,
            },
        },
    };
    use matrix_sdk::{LoopCtrl, sync::SyncResponse};

    use super::{
        COMMAND_REPLY_TEXT, build_command_reply, is_link_command, is_mentioned, persist_next_batch,
        persist_sync_token, read_sync_token, within_response_window,
    };

    fn user_id(id: &str) -> OwnedUserId {
        id.try_into().unwrap()
    }

    fn event_id(id: &str) -> OwnedEventId {
        id.try_into().unwrap()
    }

    fn event(
        id: &str,
        mentions: Option<Mentions>,
        relates_to: Option<Relation<RoomMessageEventContentWithoutRelation>>,
    ) -> OriginalSyncRoomMessageEvent {
        let mut content = RoomMessageEventContent::text_plain("hello");
        content.mentions = mentions;
        content.relates_to = relates_to;
        OriginalSyncRoomMessageEvent {
            content,
            event_id: event_id(id),
            sender: user_id("@alice:localhost"),
            origin_server_ts: MilliSecondsSinceUnixEpoch::now(),
            unsigned: MessageLikeUnsigned::new(),
        }
    }

    #[test]
    fn read_sync_token_returns_none_when_missing() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("sync-token.txt");
        assert_eq!(read_sync_token(&path), None);
    }

    #[test]
    fn persist_sync_token_creates_file_and_reads_back() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("tokens").join("sync-token.txt");
        persist_sync_token(&path, "s7259_1").unwrap();

        assert_eq!(path.metadata().unwrap().len(), "s7259_1".len() as u64);
        assert_eq!(read_sync_token(&path).as_deref(), Some("s7259_1"));
    }

    #[test]
    fn read_sync_token_trims_whitespace() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("sync-token.txt");
        std::fs::write(&path, "s7259_1\n").unwrap();
        assert_eq!(read_sync_token(&path).as_deref(), Some("s7259_1"));
    }

    #[test]
    fn read_sync_token_returns_none_for_empty_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("sync-token.txt");
        std::fs::write(&path, "\n").unwrap();
        assert_eq!(read_sync_token(&path), None);
    }

    #[tokio::test]
    async fn persist_next_batch_writes_token_and_continues() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("sync-token.txt");
        let response = SyncResponse {
            next_batch: "s7259_2".to_owned(),
            ..SyncResponse::default()
        };

        let ctrl = persist_next_batch(&path, Ok(response)).await.unwrap();
        assert_eq!(ctrl, LoopCtrl::Continue);
        assert_eq!(read_sync_token(&path).as_deref(), Some("s7259_2"));
    }

    #[test]
    fn mentions_detect_the_bot() {
        let mentioned = event(
            "$m1",
            Some(Mentions::with_user_ids(vec![user_id("@bot:localhost")])),
            None,
        );
        assert!(is_mentioned(&mentioned, &user_id("@bot:localhost")));
        assert!(!is_mentioned(&mentioned, &user_id("@someone:localhost")));
    }

    #[test]
    fn room_mentions_do_not_trigger() {
        let room_mentioned = event("$m2", Some(Mentions::with_room_mention()), None);
        assert!(!is_mentioned(&room_mentioned, &user_id("@bot:localhost")));
    }

    #[test]
    fn messages_without_mentions_do_not_trigger() {
        let plain = event("$m3", None, None);
        assert!(!is_mentioned(&plain, &user_id("@bot:localhost")));
    }

    #[test]
    fn fresh_and_old_messages_are_handled_by_the_window() {
        assert!(within_response_window(MilliSecondsSinceUnixEpoch::now()));
        let ancient = MilliSecondsSinceUnixEpoch::from_system_time(UNIX_EPOCH).unwrap();
        assert!(!within_response_window(ancient));
    }

    #[test]
    fn reply_starts_a_new_thread_rooted_at_the_message() {
        let message = event("$msg1", None, None);
        let content = build_command_reply(&message);
        let MessageType::Text(text) = content.msgtype else {
            panic!("expected text reply");
        };
        assert_eq!(text.body, COMMAND_REPLY_TEXT);
        let Relation::Thread(thread) = content.relates_to.expect("reply must be threaded") else {
            panic!("expected thread relation");
        };
        assert_eq!(thread.event_id, event_id("$msg1"));
    }

    #[test]
    fn reply_continues_an_existing_thread() {
        let message = event(
            "$msg2",
            None,
            Some(Relation::Thread(Thread::plain(
                event_id("$root"),
                event_id("$msg2"),
            ))),
        );
        let content = build_command_reply(&message);
        let Relation::Thread(thread) = content.relates_to.expect("reply must be threaded") else {
            panic!("expected thread relation");
        };
        assert_eq!(thread.event_id, event_id("$root"));
    }

    #[test]
    fn link_commands_are_detected_with_and_without_prefixes() {
        assert!(is_link_command("link", "@bot:localhost"));
        assert!(is_link_command("!link", "@bot:localhost"));
        assert!(is_link_command("@bot:localhost link", "@bot:localhost"));
        assert!(is_link_command("Link", "@bot:localhost"));
        assert!(!is_link_command("linking", "@bot:localhost"));
        assert!(!is_link_command("hello", "@bot:localhost"));
    }
}
