//! `MatrixClient` trait — the mock boundary between the bot's sync loop
//! and the matrix-sdk (item 5.25).
//!
//! The real impl wraps `matrix-sdk` and yields two kinds of events: GPX
//! file bytes received in any joined room, and `link` commands from users.
//! The test impl returns fixture events so the sync loop can be exercised
//! without a live Matrix connection.

use std::path::Path;

use async_trait::async_trait;
use matrix_sdk::{
    Client, Room, RoomState,
    config::SyncSettings,
    media::{MediaFormat, MediaRequestParameters},
    ruma::{
        EventId, OwnedEventId, OwnedRoomId, OwnedUserId, RoomId,
        events::{
            reaction::ReactionEventContent,
            relation::{Annotation, InReplyTo},
            room::{
                member::StrippedRoomMemberEvent,
                message::{
                    MessageType, OriginalSyncRoomMessageEvent, Relation, RoomMessageEventContent,
                },
            },
        },
    },
};
use tokio::sync::mpsc;
use tokio::time::sleep;

use crate::matrix_auth::{MatrixLoginConfig, get_client};

#[derive(Debug, Clone)]
pub struct GpxFileMetadata {
    pub filename: String,
    /// The Matrix user who sent the file.
    pub sender: OwnedUserId,
    pub room_id: OwnedRoomId,
    pub event_id: OwnedEventId,
}

/// Everything the sync loop can observe from Matrix.
#[derive(Debug)]
pub enum BotEvent {
    /// A `.gpx` file was sent in a joined room.
    GpxFile {
        bytes: Vec<u8>,
        metadata: GpxFileMetadata,
    },
    /// A user invoked the `link` command.
    LinkRequest {
        sender: OwnedUserId,
        room_id: OwnedRoomId,
        event_id: OwnedEventId,
    },
    /// A reply generated by a background task (e.g. the link poller),
    /// routed through the main loop so all Matrix I/O stays in one place.
    Reply {
        room_id: OwnedRoomId,
        event_id: OwnedEventId,
        text: String,
    },
}

type BotEventSender = mpsc::Sender<BotEvent>;
type BotEventSenderCtx =
    matrix_sdk::event_handler::Ctx<std::sync::Arc<tokio::sync::Mutex<BotEventSender>>>;

#[async_trait]
pub trait MatrixClient: Send + Sync {
    async fn wait_for_event(&self) -> anyhow::Result<BotEvent>;

    async fn send_text_reply(
        &self,
        room_id: &RoomId,
        event_id: &EventId,
        text: &str,
    ) -> anyhow::Result<()>;

    async fn send_html_reply(
        &self,
        room_id: &RoomId,
        event_id: &EventId,
        plain: &str,
        html: &str,
    ) -> anyhow::Result<()>;

    async fn send_reaction(
        &self,
        room_id: &RoomId,
        event_id: &EventId,
        key: &str,
    ) -> anyhow::Result<()>;
}

pub struct MatrixSdkClient {
    client: Client,
    tx: std::sync::Arc<tokio::sync::Mutex<BotEventSender>>,
    rx: std::sync::Arc<tokio::sync::Mutex<mpsc::Receiver<BotEvent>>>,
}

impl MatrixSdkClient {
    /// Build a Matrix client that yields GPX files and `link` commands
    /// received in joined rooms.
    ///
    /// # Errors
    /// Returns an error if the Matrix client cannot be built, the login
    /// fails, or the initial sync does not complete.
    pub async fn new(login: &MatrixLoginConfig, session_file: &Path) -> anyhow::Result<Self> {
        let client = get_client(login, session_file).await?;

        client.add_event_handler(on_stripped_state_member);

        let (tx, rx) = mpsc::channel::<BotEvent>(16);
        let tx = std::sync::Arc::new(tokio::sync::Mutex::new(tx));
        let rx = std::sync::Arc::new(tokio::sync::Mutex::new(rx));
        client.add_event_handler_context(tx.clone());
        client.add_event_handler(on_room_message);

        let sync_token = client.sync_once(SyncSettings::default()).await?.next_batch;
        tracing::info!("Finished initial Matrix sync");

        let sync_client = client.clone();
        tokio::spawn(async move {
            let settings = SyncSettings::default().token(sync_token);
            if let Err(e) = sync_client.sync(settings).await {
                tracing::error!("Matrix sync ended with error: {e}");
            }
        });

        Ok(Self { client, tx, rx })
    }

    /// A sender that background tasks (e.g. the link poller) can use to
    /// route [`BotEvent::Reply`] back through the main loop.
    #[must_use]
    pub fn event_sender(&self) -> std::sync::Arc<tokio::sync::Mutex<BotEventSender>> {
        self.tx.clone()
    }
}

#[async_trait]
impl MatrixClient for MatrixSdkClient {
    async fn wait_for_event(&self) -> anyhow::Result<BotEvent> {
        let mut rx = self.rx.lock().await;
        rx.recv()
            .await
            .ok_or_else(|| anyhow::anyhow!("matrix event channel closed"))
    }

    async fn send_text_reply(
        &self,
        room_id: &RoomId,
        event_id: &EventId,
        text: &str,
    ) -> anyhow::Result<()> {
        let room = self
            .client
            .get_room(room_id)
            .ok_or_else(|| anyhow::anyhow!("room {room_id} not found"))?;

        let mut content = RoomMessageEventContent::text_plain(text);
        content.relates_to = Some(Relation::Reply {
            in_reply_to: InReplyTo::new(event_id.to_owned()),
        });
        room.send(content).await?;
        Ok(())
    }

    async fn send_html_reply(
        &self,
        room_id: &RoomId,
        event_id: &EventId,
        plain: &str,
        html: &str,
    ) -> anyhow::Result<()> {
        let room = self
            .client
            .get_room(room_id)
            .ok_or_else(|| anyhow::anyhow!("room {room_id} not found"))?;

        let mut content = RoomMessageEventContent::text_html(plain, html);
        content.relates_to = Some(Relation::Reply {
            in_reply_to: InReplyTo::new(event_id.to_owned()),
        });
        room.send(content).await?;
        Ok(())
    }

    async fn send_reaction(
        &self,
        room_id: &RoomId,
        event_id: &EventId,
        key: &str,
    ) -> anyhow::Result<()> {
        let room = self
            .client
            .get_room(room_id)
            .ok_or_else(|| anyhow::anyhow!("room {room_id} not found"))?;

        let content =
            ReactionEventContent::new(Annotation::new(event_id.to_owned(), key.to_owned()));
        room.send(content).await?;
        Ok(())
    }
}

async fn on_stripped_state_member(
    room_member: StrippedRoomMemberEvent,
    client: Client,
    room: Room,
) {
    let Some(user_id) = client.user_id() else {
        tracing::error!("Could not get user id from client");
        return;
    };
    if room_member.state_key != user_id {
        return;
    }

    tokio::spawn(async move {
        // Join first — request_encryption_state() before joining tends
        // to fail because the server won't serve state to non-members.
        let mut delay = 2u64;

        while let Err(err) = room.join().await {
            tracing::error!(
                "Failed to join room {} ({err:?}), retrying in {delay}s",
                room.room_id()
            );
            sleep(std::time::Duration::from_secs(delay)).await;
            if let Some(x) = delay.checked_mul(2) {
                delay = x;
            } else {
                tracing::error!("Delay got too large, aborting");
                return;
            }
            if delay > 3600 {
                tracing::error!("Can't join room {} ({err:?})", room.room_id());
                return;
            }
        }
        tracing::info!("Successfully joined room {}", room.room_id());

        // Now check whether the room is encrypted; leave if it is.
        if let Err(e) = room.request_encryption_state().await {
            tracing::warn!(
                "Could not request encryption state for room {} ({e}), \
                 staying joined anyway",
                room.room_id()
            );
        } else if !matches!(
            room.encryption_state(),
            matrix_sdk::EncryptionState::NotEncrypted
        ) {
            tracing::error!("Room {} is encrypted, leaving", room.room_id());
            if let Err(e) = room.leave().await {
                tracing::error!("Failed to leave room {}: {e}", room.room_id());
            }
        }
    });
}

async fn on_room_message(
    event: OriginalSyncRoomMessageEvent,
    room: Room,
    client: Client,
    tx: BotEventSenderCtx,
) {
    if room.state() != RoomState::Joined {
        return;
    }
    let Some(user_id) = client.user_id() else {
        tracing::error!("Could not get user id from client");
        return;
    };
    if event.sender == user_id {
        return;
    }

    match event.content.msgtype {
        MessageType::File(file_content) => {
            let filename = file_content.filename().to_owned();
            if !std::path::Path::new(&filename)
                .extension()
                .is_some_and(|ext| ext.eq_ignore_ascii_case("gpx"))
            {
                return;
            }

            let bytes = match client
                .media()
                .get_media_content(
                    &MediaRequestParameters {
                        source: file_content.source,
                        format: MediaFormat::File,
                    },
                    false,
                )
                .await
            {
                Ok(b) => b,
                Err(e) => {
                    tracing::error!("Failed to download file {filename}: {e}");
                    return;
                }
            };

            tracing::info!("Received GPX file: {filename}");
            let _ = tx
                .lock()
                .await
                .send(BotEvent::GpxFile {
                    bytes,
                    metadata: GpxFileMetadata {
                        filename,
                        sender: event.sender,
                        room_id: room.room_id().to_owned(),
                        event_id: event.event_id.clone(),
                    },
                })
                .await;
        }
        MessageType::Text(text_content)
            if is_link_command(&text_content.body, user_id.as_str()) =>
        {
            tracing::info!("Link command from {}", event.sender);
            let _ = tx
                .lock()
                .await
                .send(BotEvent::LinkRequest {
                    sender: event.sender,
                    room_id: room.room_id().to_owned(),
                    event_id: event.event_id.clone(),
                })
                .await;
        }
        _ => {}
    }
}

/// Whether a message body is a `link` command — bare `link`, `!link`, or
/// a mention like `@health-bot link` (case-insensitive).
fn is_link_command(body: &str, bot_user_id: &str) -> bool {
    let trimmed = body.trim();
    let without_bang = trimmed.strip_prefix('!').unwrap_or(trimmed).trim();
    let without_mention = without_bang
        .strip_prefix(bot_user_id)
        .unwrap_or(without_bang)
        .trim();
    without_mention.eq_ignore_ascii_case("link")
}
